services:
  postgres-account:
    image: postgres:16
    container_name: account-postgres
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - account_postgres_data:/var/lib/postgresql/data

volumes:
  account_postgres_data: