package com.internet.banking.orchestrator.microservice.enums;

public enum CustomerSelfRegistrationSagaStatus {
    STARTED,

    CUSTOMER_CREATION_REQUESTED,
    CUSTOMER_CREATED,

    MANAGER_ASSIGNMENT_REQUESTED,
    MANAGER_ASSIGNED,

    ACCOUNT_CREATION_REQUESTED,
    ACCOUNT_CREATED,

    AUTHENTICATION_CREATION_REQUESTED,
    AUTHENTICATION_CREATED,

    COMPLETED,

    COMPENSATION_STARTED,
    ACCOUNT_CANCELLATION_REQUESTED,
    ACCOUNT_CANCELLED,

    CUSTOMER_DEACTIVATION_REQUESTED,
    CUSTOMER_DEACTIVATED,

    AUTHENTICATION_DEACTIVATION_REQUESTED,
    AUTHENTICATION_DEACTIVATED,

    FAILED
}
