version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: saga-orchestrator-postgres
    environment:
      POSTGRES_DB: sagaorchestratordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"