spring.application.name=microservice-auth
server.port=8081

# Desabilita Spring Security para todas as rotas (auth é feito pelo próprio serviço)
spring.security.user.name=disabled
spring.security.user.password=disabled