spring.application.name=microservice-auth
server.port=8081

# MongoDB — conforme docker-compose.yml (porta 27017)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://auth-mongo:27017/authdb}
spring.data.mongodb.database=authdb

# Desabilita auto-configuração do datasource (sem PostgreSQL aqui)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
