spring.application.name=customer.microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/bantadsdb?currentSchema=customer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=customer

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=customer
spring.flyway.create-schemas=true

server.port=8082

