spring.application.name=customer.microservice

spring.datasource.url=jdbc:postgresql://localhost:5435/customerdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8082

